### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by elcritch** [vindvaki/atom-autocomplete-julia#1]
[Enter steps to reproduce below:]

Tried running a non-trivial Julia instance using Hydrogen. Afterwords the auto-complete stopped working. 

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete-julia](https://github.com/vindvaki/atom-autocomplete-julia) package, v0.0.7
### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
    at Socket._writeGeneric (net.js:634:19)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at JuliaProvider.module.exports.JuliaProvider.getSuggestions (/Users/elcritch/.atom/packages/autocomplete-julia/lib/julia-provider.coffee:26:24)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
```
### Commands

```
     -0:24 core:move-right (atom-text-editor.editor.is-focused)
 18x -0:23.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:19.5.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:16 core:move-down (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:move-up (atom-text-editor.editor.is-focused)
  6x -0:14.3.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:12.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:10.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:cancel (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "unity-ui",
      "twilight-textmate-syntax"
    ],
    "projectHome": "/Users/elcritch/proj/",
    "disabledPackages": [
      "image-copipe",
      "language-ipynb",
      "markdown-format",
      "tidy-markdown",
      "markdown-lists",
      "markdown-preview-plus",
      "zotero-citations",
      "mark",
      "wrap-guide",
      "welcome",
      "linter",
      "linter-jscs",
      "minimap"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Hydrogen, v0.4.1
Sublime-Style-Column-Selection, v1.3.0
academic, v0.34.1
api-docs, v0.0.1
autocomplete-julia, v0.0.7
drop-up, v0.1.2
language-hy, v0.1.0
language-julia, v0.1.1
language-pfm, v0.69.0
markdown-preview-opener, v0.1.1
markdown-scroll-sync, v0.4.0
markdown-table-formatter, v2.5.2
repl-term, v0.1.0
twilight-textmate-syntax, v0.1.19
typewriter, v0.3.3
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by vindvaki** [comment]
Thanks for the report! 

This error means that the julia child process somehow crashed or got killed.

Do you have a sample line of code, for which this tends to happen? 

I ask, because the autocompletion provider just sends the current line of the buffer to a julia child process that then tries to apply the REPL autocompletion function from the standard library.

**Comment by davidavdav** [comment]
I get this error, too in a big red box, for every character I type.  Pretty annoying. 
- Julia is in stalled in /usr/local/bin
- which is in the path
- I start atom from the cmdline
- It is in the settings

and still atom can't find Julia.  I am stymied.

**Comment by vindvaki** [comment]
Unfortunately I don't know what was causing this. I wrote this package a long time ago as a quick and dirty hack for fun, but haven't really worked on it since. Well, I just took a further look and feel it's not really in a presentable state, so I unpublished it.
