### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by euchcat** [vindvaki/atom-autocomplete-julia#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [autocomplete-julia](https://github.com/vindvaki/atom-autocomplete-julia) package, v0.0.7
### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at JuliaProvider.module.exports.JuliaProvider.getSuggestions (/home/lionel/.atom/packages/autocomplete-julia/lib/julia-provider.coffee:18:18)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
     -8:55.7.0 editor:newline (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -8:53.6.0 snippets:next-tab-stop (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -8:53.6.0 snippets:expand (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -8:53.6.0 editor:indent (atom-text-editor.editor.mechanical-keyboard.is-focused)
  3x -8:49.3.0 core:backspace (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -8:35.7.0 core:move-down (atom-text-editor.editor.mechanical-keyboard.is-focused.autocomplete-active)
     -8:34.6.0 autocomplete-plus:confirm (atom-text-editor.editor.mechanical-keyboard.is-focused.autocomplete-active)
     -8:34.6.0 snippets:expand (atom-text-editor.editor.mechanical-keyboard.is-focused.autocomplete-active)
undefined -8:31.2.0 core:move-left (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -8:14.4.0 editor:newline (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -8:10 core:move-right (atom-text-editor.editor.mechanical-keyboard.is-focused)
  7x -8:09.8.0 editor:newline (atom-text-editor.editor.mechanical-keyboard.is-focused)
  2x -4:48.8.0 window:toggle-dev-tools (div.settings-view.pane-item)
     -1:36.1.0 core:backspace (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -1:32.9.0 core:save (atom-text-editor.editor.mechanical-keyboard.is-focused)
     -1:19 script:run (atom-text-editor.editor.mechanical-keyboard.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-python-debugger, v0.3.4
autocomplete-julia, v0.0.7
language-julia, v0.3.1
mechanical-keyboard-1, v0.1.3
script, v2.26.3

# Dev
No dev packages
```

**Comment by euchcat** [comment]
This, after launching the same script with a terminal...
Good job for your work !
Greetings.
