### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by burbma** [vindvaki/atom-autocomplete-julia#4]
[Enter steps to reproduce below:]
1. Have Mac OSX 10.11.0
2. Install atom-autocomplete-julia
3. Upgrade to Mac OSX 10.11.1
4. Run atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [autocomplete-julia](https://github.com/vindvaki/atom-autocomplete-julia) package, v0.1.0
### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
  at exports._errnoException (util.js:814:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:343:9)
  at new JuliaProvider (/Users/matt/.atom/packages/autocomplete-julia/lib/julia-provider.coffee:13:14)
  at /Users/matt/.atom/packages/autocomplete-julia/lib/atom-autocomplete-julia.coffee:16:23
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/config.js:568:20
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Config.module.exports.Config.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/config.js:753:29)
  at Config.module.exports.Config.setRawValue (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/config.js:545:19)
  at Config.module.exports.Config.set (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/config.js:215:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:242:26
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1276:25

```
### Commands

```
 17x -0:07.0 core:backspace (atom-text-editor#autocomplete-julia.juliaPath.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "slime"
    ],
    "disabledPackages": [
      "bracket-matcher",
      "tabs",
      "better-brackets"
    ]
  },
  "autocomplete-julia": {
    "juliaPath": "/usr"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-julia, v0.1.0
autocomplete-python, v0.9.4
fonts, v1.0.0
language-julia, v0.4.1
linter, v1.10.0
linter-pep8, v1.0.1
slime, v1.3.0

# Dev
No dev packages
```

**Comment by vindvaki** [comment]
I think you need to point the package to where julia is installed in the configuration

**Comment by burbma** [comment]
I tried that in the settings a few days ago when I posted the issue and it didn't help. I've had the package disabled since. I just enabled it to try it again and it seems to be working just fine without me pointing to where julia is installed as it did before before I upgraded MacOS. Not sure what the deal is. Thanks for responding, and for the great package!
